SELECT AUTHOR as author_id, comments_count
FROM (
  SELECT AUTHOR, COUNT(COMMENTS.NEWS_NEWS_ID) as comments_count
  FROM NEWS_AUTHOR
  JOIN COMMENTS ON NEWS_AUTHOR.NEWS = COMMENTS.NEWS_NEWS_ID
  GROUP BY AUTHOR
);