SELECT tag_name
FROM(
SELECT COUNT(tag_name) as popular, tag_name 
FROM(
  SELECT TAG.TAG_NAME as tag_name, AUTHOR.AUTHOR_NAME
  FROM NEWS
  JOIN NEWS_AUTHOR ON NEWS.NEWS_ID = NEWS_AUTHOR.NEWS
  JOIN AUTHOR ON NEWS_AUTHOR.AUTHOR = AUTHOR.AUTHOR_ID
  JOIN NEWS_TAG ON NEWS.NEWS_ID = NEWS_TAG.NEWS
  JOIN TAG ON NEWS_TAG.TAG = TAG.TAG_ID
  WHERE AUTHOR.AUTHOR_ID = 82
)
GROUP BY tag_name
ORDER BY popular DESC
)
WHERE ROWNUM < 2;

-- need to remove number of joins