SELECT DISTINCT FIRST_VALUE(tag_name) OVER (PARTITION BY COUNT(tag_name)) "Most popular tag"
FROM(
  SELECT COUNT(tag_name) as popularity, tag_name
  FROM(
    SELECT TAG.TAG_NAME as tag_name, AUTHOR.AUTHOR_NAME
    FROM NEWS
    JOIN NEWS_AUTHOR ON NEWS.NEWS_ID = NEWS_AUTHOR.NEWS
    JOIN AUTHOR ON NEWS_AUTHOR.AUTHOR = AUTHOR.AUTHOR_ID
    JOIN NEWS_TAG ON NEWS.NEWS_ID = NEWS_TAG.NEWS
    JOIN TAG ON NEWS_TAG.TAG = TAG.TAG_ID
  )
  GROUP BY tag_name
  ORDER BY popularity DESC
)
GROUP BY tag_name;