CREATE OR REPLACE TRIGGER COMMENT_LOGGER
BEFORE INSERT ON COMMENTS FOR EACH ROW
DECLARE 
  report VARCHAR2(4000); 
BEGIN

  report := '"TEXT" : "' || :NEW.TEXT || '"';
  report := ADD_TO_LOG(report, 'CREATION_DATE', :NEW.CREATION_DATE);
  report := report || '; "NEWS_ID" : "' || :NEW.NEWS_NEWS_ID || '"';
  
  INSERT INTO LOGGING (INSERT_TIME, TABLE_NAME, TEXT)
  VALUES(SYSDATE, 'COMMENTS', report);
END;