CREATE OR REPLACE TRIGGER NEWS_LOGGER
BEFORE INSERT ON NEWS FOR EACH ROW
DECLARE 
  report VARCHAR2(4000); 
BEGIN

  report := ADD_TO_LOG(report, 'TITLE', :NEW.TITLE);
  report := ADD_TO_LOG(report, 'SHORT_TEXT', :NEW.SHORT_TEXT);
  report := ADD_TO_LOG(report, 'FULL_TEXT', :NEW.FULL_TEXT);
  report := ADD_TO_LOG(report, 'CREATION_DATE', :NEW.CREATION_DATE);
  report := ADD_TO_LOG(report, 'MODIFICATION_DATE', :NEW.MODIFICATION_DATE);
  
  INSERT INTO LOGGING (INSERT_TIME, TABLE_NAME, TEXT)
  VALUES(SYSDATE, 'NEWS', report);
END;