-- version 1
CREATE OR REPLACE VIEW TABLESIZES_1_VIEW AS
SELECT SEGMENT_NAME "Table", SUM(BYTES / 1024 / 1024) "Size in MB", SUM(BLOCKS) "Number of blocks"
FROM DBA_SEGMENTS
WHERE segment_type='TABLE'
AND OWNER = 'NEWSMAN'
GROUP BY SEGMENT_NAME;

CREATE OR REPLACE VIEW TABLESIZES_2_VIEW AS
-- version 2
SELECT SEGMENT_NAME as "Table", SUM(EXTENTS) as "Extents", ((SUM(EXTENTS) - 1) * 1048576 + 65536)/1024/1024 as "Size (MB)"
FROM DBA_SEGMENTS
WHERE OWNER = 'NEWSMAN'
AND SEGMENT_TYPE = 'TABLE'
GROUP BY SEGMENT_NAME;